language: php

sudo: false

before_script:
  - pyrus install pear/PHP_CodeSniffer-1.5.6
  # - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs -p --report=full --extensions=php --standard=./build/Joomla/ruleset.xml src/
