language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  # - composer update
  - pyrus install pear/PHP_CodeSniffer-1.5.6
  # - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  # - ./vendor/bin/phpunit
  - phpcs -p --report=full --extensions=php --standard=./build/Joomla_coding_standards/ruleset.xml src/