language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs -p --report=full --extensions=php --standard=./build/Joomla/ruleset.xml src/